### PR TITLE
Resolve #12

### LINKED ISSUE #12: TypeError: Cannot read property 'length' of undefined
Whenever a search doesn't result in any torrents being found the `data` variable in the `_formatPage(res, date)` function in the `RSS` module throws a TypeError exception because it tries to access the `length` property in the `data` variable (which is undefined) for the `total_results` property in the object that the function returns.

### PR DESCRIPTION
**Pull request by Serializator**
Resolves Issue https://github.com/ChrisAlderson/extratorrent-api/issues/12

### CODE REVIEW

File: lib/RSS.js [hunk 1]
```diff
@@ -11,13 +11,17 @@ module.exports = class RSS extends Helper {
...
       page: NaN,
-      total_results: data.length,
+      total_results: 0,
       total_pages: NaN,
-      results: data.map(item => {
+      results: []
+    };
+
+    if(data !== undefined) {
+      data['total_results'] = data.length;
```
Comment (ChrisAlderson) [inline lib/RSS.js]: Should refer to the `result` object not the `data` object. Also please use the dot notation, instead of the square bracket notation for accessing the `total_results` attribute.

File: lib/RSS.js [hunk 2]
```diff
@@ -11,13 +11,17 @@ module.exports = class RSS extends Helper {
...
+      data['results'] = data.map(item => {
```
Comment (ChrisAlderson) [inline lib/RSS.js]: Same thing as L23.

File: lib/RSS.js [hunk 3]
```diff
@@ -11,13 +11,17 @@ module.exports = class RSS extends Helper {
...
       response_time: parseInt(date, 10),
       page: NaN,
-      total_results: data.length,
+      total_results: 0,
       total_pages: NaN,
-      results: data.map(item => {
+      results: []
+    };
+
+    if(data !== undefined) {
```
Comment (ChrisAlderson) [inline lib/RSS.js]: I know it's nitpicking, but a space between the `if` and the parenthesis.

**Review by ChrisAlderson — CHANGES_REQUESTED** [review]

**Comment by Serializator** [comment]
Stupid mistakes because of carelessness and the urge to quickly fix something, pushed the changes and did a rebase to keep it a single commit.

What about the failed Travis builds, it seem to be tests that are not related to the changes made by my commit, or did my changes affect the `Website` module in some weird way that I don't know about?

**Comment by ChrisAlderson** [comment]
Changes look good, thanks for finding and fixing the bug.

The `Website` module is only failing because of the `baseUrl`. Your commit didn't change anything in the `Website` module. I'll merge this PR and fix the `Website` module, making it version `1.1.4`.
